# Generated by Django 5.0.3 on 2024-05-08 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Admin', max_length=200)),
                ('petname', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption1.category')),
            ],
        ),
        migrations.CreateModel(
            name='Featured_Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption1.pet')),
            ],
        ),
    ]
