# Generated by Django 5.0.3 on 2024-05-10 01:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption1', '0002_category_pet_featured_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('comment_text', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption1.pet')),
            ],
        ),
    ]
